### PR TITLE
Committing two classes. One is the panel for the parent frame. There …

### PR DESCRIPTION
**Pull request by mvanhaver**
…is still a main method and frame object in this class that I was using for local testing. That should be able to easily be removed. I also added a separate class for an action listener.

### CODE REVIEW

**Review by tomatogrove — COMMENTED** [review]
looks good so far just make sure to remove the jframe and and the back button. Once those changes are made you can go ahead and merge

**Comment by mvanhaver** [comment]
Is there an action listener class already done for the back button that I can add to the back button I have in the panel?

**Comment by mvanhaver** [comment]
Never mind. I see it in the zip you shared.

**Comment by mvanhaver** [comment]
I removed the JFrame and added back button functionality.

**Pull request merged**
